name: CI
on: [push, pull_request]
jobs:
  build-objects:
    name: Build objects
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download gxc
      run: |
        curl -Lo tools.tar.gz https://github.com/IntelOrca/libsawyer/releases/download/v1.2.0/libsawyer-tools-linux-x64.tar.gz
        mkdir -p "$GITHUB_WORKSPACE/bin"
        tar -C "$GITHUB_WORKSPACE/bin" -xf tools.tar.gz
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
    - name: Create objects.zip
      run: ./build.mjs
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: "ZeeMajora Custom Objects"
        path: artifacts/objects.zip
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        fail_on_unmatched_files: true
        files: artifacts/objects.zip
